#!/bin/sh

set -ex

whiskers ./templates/settings.json.tera
whiskers ./templates/themes.json.tera

for path in ./dist/*/; do
  files=$(find "${path}" -type f -printf "%P\n")
  theme=$(realpath --relative-to "./dist/" "${path}")
  # shellcheck disable=SC2086 # Double quote to prevent globbing and word splitting
  tar --create --directory "${path}" --file "./dist/${theme}.tar.gz" --gzip ${files}
done
