[tool.poetry]
name = "chatterino2"
version = "0.1.0"
description = ""
authors = ["fruzitent <fruzit@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
