[tool.poetry]
name = "chatterino2"
version = "0.1.0"
description = ""
authors = ["fruzitent <fruzit@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
black = "^23.9.1"
flake8-pyproject = "^1.2.3"
wemake-python-styleguide = "^0.18.0"

[tool.poetry.group.typing]
optional = true

[tool.poetry.group.typing.dependencies]
mypy = "^1.5.1"

[tool.poetry.dependencies]
python = "^3.11"
