on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version-file: "./pyproject.toml"

      - name: Install dependencies
        run: pip install -e .

      - name: Generate themes
        run: python3 src/main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*.tar.gz
