on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Whiskers
        run: |
          wget -O "/usr/local/bin/whiskers" "https://github.com/catppuccin/whiskers/releases/download/v2.4.0/whiskers-x86_64-unknown-linux-gnu"
          chmod +x /usr/local/bin/whiskers

      - name: Generate themes
        run: |
          chmod +x ./build
          ./build
          ls -lah ./dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*.tar.gz
